Vclean/Models/CompanyView.cs
namespace Vclean.Models
{
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using Common.Models;

    [NotMapped]
    public class CompanyView : Company
    {
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

Vclean/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vclean.Common.Models;
using Vclean.Models;
using Vclean.Helpers;

namespace Vclean.Controllers
{
    public class CompaniesController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Companies
        public async Task<ActionResult> Index()
        {
            return View(await db.Companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var company = await db.Companies.FindAsync(id);

            if (company == null)
            {
                return HttpNotFound();
            }

            var view = new DetailCompanyView
            {
                Name = company.Name,
                CompanyId = company.CompanyId,
                CompanyCode = company.CompanyCode,
                ImagePath = company.ImagePath,
                Sites = company.Sites
            };

            return View(view);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CompanyView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/Images/CompanyLogo";

                if(view.ImageFile != null)
                {
                    pic = FileHelper.UploadFile(view.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var company = new Company
                {
                    CompanyCode = view.CompanyCode,
                    ImagePath = pic,
                    Name = view.Name
                };

                db.Companies.Add(company);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        // GET: Companies/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var company = await db.Companies.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }

            var view = new CompanyView
            {
                Name = company.Name,
                CompanyCode = company.CompanyCode,
                CompanyId = company.CompanyId,
                ImagePath = company.ImagePath                
            };

            return View(view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CompanyView view)
        {
            if (ModelState.IsValid)
            {
                var pic = view.ImagePath;
                var folder = "~/Content/Images/CompanyLogo";

                if (view.ImageFile != null)
                {
                    pic = FileHelper.UploadFile(view.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var company = new Company
                {
                    Name = view.Name,
                    CompanyCode = view.CompanyCode,
                    CompanyId = view.CompanyId,
                    ImagePath = pic
                };

                db.Entry(company).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(view);
        }

        // GET: Companies/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Company company = await db.Companies.FindAsync(id);
            db.Companies.Remove(company);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddSite(DetailCompanyView view)
        {
            //Don't need validate the model because only is using one string
            var site = new Site
            {
                SiteName = view.SiteName,
                Address = view.Address,
                OptionalAddress = view.OptionalAddress,
                City = view.City,
                PostCode = view.PostCode,
                CompanyId = view.CompanyId                
            };

            db.Sites.Add(site);
            await db.SaveChangesAsync();

            return RedirectToAction($"Details/{view.CompanyId}");

        }

        public async Task<ActionResult> EditSite(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var site = await db.Sites.FindAsync(id);
            if (site == null)
            {
                return HttpNotFound();
            }

            var view = new Site
            {
                CompanyId = site.CompanyId, 
                SiteName = site.SiteName,
                SiteId = site.SiteId,
                Address = site.Address,
                OptionalAddress = site.OptionalAddress,
                City = site.City,
                PostCode = site.PostCode
            };

            return View(view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditSite(Site site)
        {
            if (ModelState.IsValid)
            {
                

                db.Entry(site).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction($"Details/{site.CompanyId}");
            }
            return View(site);
        }

        public async Task<ActionResult> DeleteSite(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var site = await db.Sites.FindAsync(id);
            if (site == null)
            {
                return HttpNotFound();
            }

            db.Sites.Remove(site);
            await db.SaveChangesAsync();

            return RedirectToAction($"Details/{site.CompanyId}");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vclean/Views/Companies/Create.cshtml
@model Vclean.Models.CompanyView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Companies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Company</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompanyCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CompanyCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span class="btn btn-default btn-file">
                @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
            </span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vclean/Views/Companies/Delete.cshtml
@model Vclean.Common.Models.Company

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Vclean/Views/Companies/Details.cshtml
@model Vclean.Models.DetailCompanyView

@{
    ViewBag.Title = "Details";
}



<div>



    <h2>@Html.DisplayFor(model => model.Name)</h2>
    @if (!string.IsNullOrEmpty(Model.ImagePath))
    {
        <img src="@Url.Content(Model.ImagePath)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto; border-style:solid; border:1;" />
    }

</div>

<hr />
@Html.ActionLink("Back to List", "Index", " ", new { @class = "pull-right" })
<h4>Sites</h4>

<div class="container bg-info" style="height:54px;">
    @using (Html.BeginForm("AddSite", "Companies", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CompanyId)

        <div class="form-inline" style="padding: 10px; margin-left: 30px;">
            <div class="form-group">
                @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Building" } })
                @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.OptionalAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "Optional address" } })
                @Html.ValidationMessageFor(model => model.OptionalAddress, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", @placeholder = "City" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Post code" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-outline-info pull-right" />
            </div>
        </div>
    }
</div>
<p></p>
@if (Model.Sites.Count == 0)
{
    <h5>No Sites</h5>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Sites.FirstOrDefault().SiteName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sites.FirstOrDefault().Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sites.FirstOrDefault().OptionalAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sites.FirstOrDefault().City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sites.FirstOrDefault().PostCode)
            </th>
            <th>

            </th>
        </tr>

        @foreach (var item in Model.Sites)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SiteName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OptionalAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostCode)
                </td>
                <td>
                    <a href="@Url.Action("EditSite","Companies", new { id = item.SiteId })" style="text-decoration:none; color:orange;">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a> &nbsp; | &nbsp;

                    <a href="@Url.Action("DeleteSite","Companies", new { id = item.SiteId })" style="text-decoration:none; color: red;">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </table>
}

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.CompanyId }) |*@

</p>

Vclean/Views/Companies/Edit.cshtml
@model Vclean.Models.CompanyView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Companies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Company</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CompanyId)
    @Html.HiddenFor(model => model.ImagePath)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CompanyCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompanyCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CompanyCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span class="btn btn-default btn-file">
                @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
            </span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Vclean/Views/Companies/EditSite.cshtml
@model Vclean.Common.Models.Site
@{
    ViewBag.Title = "EditSite";
}

<h2>EditSite</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Company</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SiteId)
    @Html.HiddenFor(model => model.CompanyId)

    <div class="form-group">
        @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OptionalAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OptionalAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OptionalAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

Vclean/Views/Companies/Index.cshtml
@model IEnumerable<Vclean.Common.Models.Company>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sites)
        </th>
        <th>

        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyCode)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.ImagePath))
            {
                <img src="@Url.Content(item.ImagePath)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            }            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sites.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CompanyId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CompanyId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CompanyId })
        </td>
    </tr>
}

</table>